# Generated by Django 4.2.13 on 2026-06-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_activated_activationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("admin", "Admin"),
                    ("expert", "Expert"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
