# Generated by Django 4.2.13 on 2026-06-05 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_ticket",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_ticket_reply",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_messages",
                to="chat.ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="response_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="tickets/responses/"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="response_text",
            field=models.TextField(blank=True),
        ),
    ]
