# Generated by Django 4.2.13 on 2026-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_is_ticket_message_is_ticket_reply_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="exam_title",
            field=models.CharField(
                blank=True,
                help_text="Human-readable exam title (e.g., FMP Oujda 2013)",
                max_length=300,
            ),
        ),
    ]
